DefaultContentLanguage = "en"
Paginate = 6
SectionPagesMenu = "main"
baseURL = "https://thank-you-st-rice.github.io/gphugo/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "novela"
title = "Thank You, St. Rice"
[params]
description = "A free blog for you to clone and have your own"
favicon = ""
site_logo = ""
[params.share]
facebook = true
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
author = "authors"
