image:
  file: .gitpod.Dockerfile

tasks:
  - init: git submodule update --init && git worktree add -B firebase-public public origin/firebase-public
    command: hugo server --baseUrl $(gp url 1313) --appendPort=false --environment gitpod

ports:
  - port: 1313
    onOpen: open-preview