image:
  file: .gitpod.Dockerfile

tasks:
  - init: git submodule update --init && git worktree add -B gh-pages gphugo/public origin/gh-pages
    command: hugo server --baseUrl $(gp url 1313)/gphugo --appendPort=false -s gphugo && gp preview $(gp url 1313)/gphugo

ports:
  - port: 1313
    onOpen: ignore