image:
  file: .gitpod.Dockerfile

tasks:
  - init: git submodule update --init
    command: hugo server --baseUrl $(gp url 1313) --appendPort=false -s gphugo

ports:
  - port: 1313
    onOpen: open-preview