baseURL = "https://ryanjbartley.github.io/gphugo/"
languageCode = "en-us"
title = "Gitpod Hugo Pipeline Development Blog"
theme = "novela"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "A blog while I work"
  [params.share]
  facebook = true

[taxonomies]
  author = "authors"